version: '3.8'
services:
  nginx_gateway:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./apps:/var/www
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
